name: Android PR

on:
  pull_request:
    branches: [ "develop" ]


concurrency:
  group: ${{ github.ref }}

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Spotless Apply
        run: ./gradlew spotlessApply --scan
      - name: Spotless
        run: ./gradlew spotlessCheck
  test:
    name: Unit tests
    runs-on: ubuntu-22.04
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
      - uses: ./.github/workflows/caches
        with:
          key-prefix: gradle-test
      - name: Unit tests
        run: ./gradlew :data:local:test
      - name: Upload test results
        uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: testDebugUnitTest
          path: ./**/build/reports/tests/testDebugUnitTest
